#!/bin/bash
CPUFREQ=$(LANG=en cpufreq-info | grep -m1 "hardware limits:" | grep -Eo "\S+ GHz$" | grep -Eo "^\S+")
CPUFREQ=$(echo "$CPUFREQ * 1000000000" | bc)
TESTFILE=tmp
TESTSIZE=$((100*1024*1024))
dd if=/dev/urandom of=$TESTFILE count=$(($TESTSIZE/512)) 2>&1 > /dev/null
echo "Test file ready"

# HASH FUNCTIONS
function bench_hash()
{
	name=$1
	(time ${name}sum $TESTFILE         > ref_res) 2> ref_tim
	(time ./crypt hash $name $TESTFILE > our_res) 2> our_tim

	if ! diff ref_res our_res
	then
		echo "$name: mismatch !"
		exit 1
	fi

	ref_tim=$(grep ^user ref_tim | awk -F'[\tms]' '{print $3 "*60 +" $4}' | bc)
	our_tim=$(grep ^user our_tim | awk -F'[\tms]' '{print $3 "*60 +" $4}' | bc)

	ref_cpb=$(echo "scale=2; $ref_tim * $CPUFREQ / $TESTSIZE" | bc)
	our_cpb=$(echo "scale=2; $our_tim * $CPUFREQ / $TESTSIZE" | bc)

	ratio=$(echo "scale=2; $our_tim / $ref_tim" | bc)

	echo -e "$name:\t$our_cpb\t/\t$ref_cpb\t= $ratio"

	rm ref_res ref_tim
	rm our_res our_tim
}
bench_hash "md5"
bench_hash "sha1"
bench_hash "sha256"
bench_hash "sha224"
bench_hash "sha512"
bench_hash "sha384"


# CIPHERS
function bench_cipher()
{
	name=$1
	(time ./crypt encrypt $name $TESTFILE $TESTFILE > /dev/null) 2> our_tim

	our_tim=$(grep ^user our_tim | awk -F'[\tms]' '{print $3 "*60 +" $4}' | bc)
	our_cpb=$(echo "scale=2; $our_tim * $CPUFREQ / $TESTSIZE" | bc)

	echo -e "$name:\t$our_cpb\n"

	rm our_tim
}
bench_cipher "des"
bench_cipher "aes128"
bench_cipher "aes192"
bench_cipher "aes256"
